AllCops:
  Excludes:
    - config/unicorn.rb
    - db/schema.rb
    - db/migrate/*
  RunRailsCops: true
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - ruby19
    - hash_rockets
