AllCops:
  Excludes:
    - config/unicorn.rb
    - db/schema.rb
    - db/migrate/*
  RunRailsCops: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  SupportedStyles:
    - hash_rockets
    - ruby19

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
