language: ruby
rvm:
- 2.2.0
script:
- npm install bower
- bower install --verbose
- bundle exec rake db:schema:load
- bundle exec rspec --color --format documentation
before_script:
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database chancellor_test;'
notifications:
  slack:
    secure: EtnoVfqVZrvMVxFaBuwrM6RhuVZvG5DA2pUab7jhFnQWah00pse2BzyhmWEgFtL/fy+2UWFT8NWF1IhpvaMwaQlQy3EgTHB/N4bsiIwZAN2UcqYZFjhm+c1bpQJZwH+jdhGSAdbeyaFuZjEGa0EX5tAO922kW7ZvSpw3qMVMT7M=
