language: ruby
rvm:
  - 2.1.5
script:
  - npm install -g bower
  - bundle exec rake db:schema:load
  - bundle exec rake bower:install
  - bundle exec rspec --color --format documentation
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - cp config/smtp.example.yml config/smtp.yml
  - mysql -e 'create database chancellor_test;'
