default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default  
  database: chancellor 
  host: localhost
  username: westernmilling

test:
  <<: *default
  database: test_chancellor
  host: localhost
  username: westernmilling

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] %>
  port: 5432
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
